// <auto-generated />
using System;
using DM.Infrastructure.DB.SqlServer.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DM.Infrastructure.DB.SqlServer.EFCore.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DM.Domain.Core.ColleagueDiscountAgg.Entities.ColleagueDiscount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ColleagueDiscounts");
                });

            modelBuilder.Entity("DM.Domain.Core.CustomerDiscountAgg.Entities.CustomerDiscount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomerDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(721),
                            DiscountRate = 40,
                            EndDate = new DateTime(2024, 7, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(668),
                            IsRemoved = false,
                            ProductId = 4L,
                            Reason = "جشنواره",
                            StartDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(482)
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(940),
                            DiscountRate = 25,
                            EndDate = new DateTime(2024, 7, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(919),
                            IsRemoved = false,
                            ProductId = 3L,
                            Reason = "جشنواره",
                            StartDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(904)
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(1008),
                            DiscountRate = 10,
                            EndDate = new DateTime(2024, 7, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(992),
                            IsRemoved = false,
                            ProductId = 1L,
                            Reason = "جشنواره",
                            StartDate = new DateTime(2024, 6, 29, 7, 53, 33, 302, DateTimeKind.Local).AddTicks(979)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
